DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS REGION;

CREATE TABLE IF NOT EXISTS USER(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  USERNAME TEXT not null,
  PASSWORD TEXT not null,
  EMAIL TEXT
);

CREATE TABLE IF NOT EXISTS EVENT(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  EVENT_ID TEXT NOT NULL,
  SOURCE TEXT,
  NAME TEXT,
  DESCRIPTION TEXT,
  START_TIME INT,
  END_TIME INT,
  -- embedded
  LOCATION_NAME TEXT,
  COUNTRY TEXT,
  REGION TEXT,
  LOCALITY TEXT,
  STREET_ADDRESS TEXT,
  LONGITUDE REAL,
  LATITUDE REAL,
  -- -------
  ORGANIZER TEXT,
  URL TEXT,
  VIRTUAL BOOLEAN,
  LAST_UPDATE TIMESTAMP,
  STATUS TEXT
);


CREATE TABLE IF NOT EXISTS REGION (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  NAME TEXT,
  LATITUDE REAL,
  LONGITUDE REAL,
  RADIUS REAL,
  OWNER INTEGER,
  LAST_SCAN TIMESTAMP

  -- CONSTRAINT fk_region_owner FOREIGN KEY(OWNER) REFERENCES USER(ID) ON DELETE SET NULL
);
